Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/08/2019
Var
   // Seção de Declarações das variáveis
   n1:real
   D:real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Informe um numero: ")
   leia(n1)
   D<-n1+n1
   escreva("O dobro de", n1," é: ",D)
Fimalgoritmo