Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/08/2019
Var
   // Seção de Declarações das variáveis
   total:real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Insira o total de vendas :")
   leia(total)
   escreva("Comissão do Vendedor =", 10*total/100)
Fimalgoritmo