Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/08/2019
Var
   // Seção de Declarações das variáveis
   dolar:real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Valor da moeda:")
   leia(dolar)
   escreva("Valor convertido =", dolar*4.15)
Fimalgoritmo